keppler_blog/config/routes.rb
KepplerBlog::Engine.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'


	 scope :admin, :blog do
     get '(search/:search)', to: 'blog#query', as: :blog_query
  	resources :posts do 
      get 'find/subcategories', action: :subcategories_of_cagegory, on: :collection
      get '(page/:page)', action: :index, on: :collection, as: 'search'
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :categories do
      get '(page/:page)', action: :index, on: :collection, as: 'search'
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
  end

  

  scope :blog do
    get '(page/:page)', to: 'blog#index', as: :blog_listing
    get ":type/:permalink", to: 'blog#filter', as: :filter
    get "category/:category/subcategory/:subcategory", to: 'blog#filter_subcategory', as: :filter_subcategory
    get '/:permalink', to: 'blog#show', as: :blog_show_post
   
  end

end

keppler_blog/app/models/keppler_blog/category.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerBlog
  class Category < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    before_save :create_permalink
    has_many :posts, dependent: :destroy
    has_many :subcategories
    accepts_nested_attributes_for :subcategories, :reject_if => :all_blank, :allow_destroy => true

    #actualizar document de elasticsearch (ojo: no sabemos si es la mejor solucion.)
    #se deberia usar __elasticsearch__.update_document pero aparantemente no funciona.
    after_commit on: [:update] do
      __elasticsearch__.index_document
    end

    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:id, :name, :subcategories] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name,
        subcategories: self.subcategories.map { |subcategory| subcategory.name } .join(", ")
      }.as_json
    end

    private

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

  end
  #Category.import
end

keppler_blog/app/models/keppler_blog/post.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerBlog
  class Post < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    is_impressionable :counter_cache => true, :column_name => :views
    before_save :create_permalink
    mount_uploader :image, ImageUploader
    belongs_to :user
    belongs_to :category
    belongs_to :subcategory
    acts_as_taggable
    acts_as_taggable_on :tags
    
    validates_presence_of :title, :body, :category_id
    validates_uniqueness_of :title

    #actualizar document de elasticsearch (ojo: no sabemos si es la mejor solucion.)
    #se deberia usar __elasticsearch__.update_document pero aparantemente no funciona.
    after_commit on: [:update] do
      puts __elasticsearch__.index_document
    end
    
    def self.published
      where(public: true).order(created_at: :desc)
    end
    
    def self.filter_by_autor(autor)
      where(public: true, user: User.find_by_permalink(autor).id).order(created_at: :desc)
    end

    def self.filter_by_category(category)
      where(public: true, category: Category.find_by_permalink(category).id).order(created_at: :desc)
    end

    def self.filter_by_tag(tag)
      where(public: true).tagged_with(tag.gsub("-", " ")).order(created_at: :desc)
    end

    def self.filter_by_subcategory(category, subcategory)
      Category.find_by_permalink(category).subcategories.find_by_permalink(subcategory).posts.order(created_at: :desc)
    end

    #search para el admin
    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:id, :title, :body, :category, :autor, :subcategory, :public, :comments, :shared, :tags], operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        title: self.title,
        body: ActionView::Base.full_sanitizer.sanitize(self.body, tags: []),
        autor: self.user.name,
        category: self.category.name,
        subcategory: self.subcategory ? self.subcategory.name : "--subcategoria",
        public: self.public ? "si--publicado" : "no--publicado",
        comments: self.comments_open ? "si--comentarios" : "no--comentarios",
        shared: self.shared_enabled ? "si--compartiendo" : "no--compartiendo",
        tags: self.tag_list.to_s
      }.as_json
    end

    def impression_count
      impressions.size
    end

    def unique_impression_count
      impressions.group(:ip_address).size #UNTESTED: might not be correct syntax
    end

    private

    def create_permalink
      self.permalink = self.title.downcase.parameterize
    end

  end
  #Post.import
end

keppler_blog/app/models/keppler_blog/subcategory.rb
module KepplerBlog
  class Subcategory < ActiveRecord::Base
  	before_save :create_permalink
  	belongs_to :category
  	has_many :posts

  	private
  	
  	def create_permalink
      self.permalink = self.name.downcase.parameterize
    end
  end
end

keppler_blog/app/controllers/keppler_blog/application_controller.rb
module KepplerBlog
  class ApplicationController < ::ApplicationController
  	protect_from_forgery except: :index
  end
end

keppler_blog/app/controllers/keppler_blog/blog_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class BlogController < ApplicationController 
    protect_from_forgery except: :index
    impressionist :actions=>[:show]

    layout 'frontend/application'
    before_action :set_data_widgets, only: [:index, :show, :filter, :filter_subcategory]

    def index
      @categories = Category.all.order(:name)

     # @posts = Post.searching(params[:query]).where(public: true).page(@current_page).per(KepplerBlog.posts_per_page)
      @posts = KepplerBlog::Category.where.not(permalink: "ultimas-noticias").map { |c| KepplerBlog::Post.where(category_id: c.id, public: true).last }

      #Delete elementos vacios
      @posts.delete([]) 
      
      #Posts mas vistos
      @posts_more_view = KepplerBlog::Post.where(public:true).order('views DESC').limit(3)

      #Post software
      @category_software = KepplerBlog::Category.find_by_permalink("software")
      @posts_software = KepplerBlog::Post.where(public:true, category_id: @category_software.id).order("created_at DESC").page(@current_page).per(6)


      #Post Hardware
      @category_hardware = KepplerBlog::Category.find_by_permalink("hardware")
      @posts_hardware = KepplerBlog::Post.where(public:true, category_id: @category_hardware.id).order("created_at DESC").page(@current_page2).per(6)
      
      # Ultimas noticias
      @category_news = KepplerBlog::Category.find_by_permalink("ultimas-noticias")
      @posts_breaking_news = KepplerBlog::Post.where(public:true, category_id: @category_news.id).order("created_at DESC").page(@current_page3).per(6)

      #POST GUIAS
      @category_guias = KepplerBlog::Category.find_by_permalink("guias")
      
      @posts_guias = KepplerBlog::Post.where(category_id: @category_guias.id, public:true).first(3)
      respond_to do |format|
        format.html
        format.js   
      end
    end

    def query
      @posts = Post.searching(params[:query]).where(public: true).page(@current_page).per(8)
      @categories = Category.all.order(:name)
    end

    def show   
      @post =  Post.find_by_permalink(params[:permalink])
      impressionist(@post) 
    end

    def filter
      @posts = Post.send("filter_by_#{params[:type]}", params[:permalink]).page(@current_page).per(8)
      render action: 'query'
    end

    def filter_subcategory
      @posts = Post.filter_by_subcategory(params[:category], params[:subcategory]).page(@current_page).per(8)
      render action: 'query'
    end

    private

    def set_data_widgets
      @posts_recents = Post.where(public: true).order("created_at DESC").first(6)
      @categories = Category.all.order(:name)
    end

  end
end

keppler_blog/app/controllers/keppler_blog/categories_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class CategoriesController < ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    # GET /categories
    def index
      categories = Category.searching(@query).all
      @objects, @total = categories.page(@current_page), categories.size
      redirect_to categories_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /categories/1
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: 'Categoría creada satisfactoriamente'
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Categoría actualizada satsfactoriamente'
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Categoría eliminada satisfactoriamente'
    end

    def destroy_multiple
      Category.destroy redefine_ids(params[:multiple_ids])
      redirect_to categories_path(page: @current_page, search: @query), notice: "Categorías eliminadas satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def category_params
        params.require(:category).permit(:name, subcategories_attributes: [:id, :name, :_destroy])
      end
  end
end

keppler_blog/app/controllers/keppler_blog/posts_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class PostsController < ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource except: [:subcategories_of_cagegory]
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :set_categories, only: [:new, :edit, :update, :create]

    # GET /posts
    def index
      posts = current_user.has_role?(:autor) ? Post.searching(@query).where(user_id: current_user.id) : Post.searching(@query).all
      @objects, @total = posts.page(@current_page), posts.size
      redirect_to posts_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /posts/1
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    def create
      @post = Post.new(post_params.merge(user_id: current_user.id))

      if @post.save
        redirect_to @post, notice: 'Post creado satisfactoriamente'
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      @post.subcategory_id = nil if post_params[:subcategory_id].nil?
      
      if @post.update(post_params)
        redirect_to @post, notice: 'Post actualizado satisfactoriamente'
      else
        render :edit
      end
    end


    def subcategories_of_cagegory
      @category = Category.find(params[:category_id])
      @subcategories = @category.subcategories
      respond_to do |format|
         format.js {  }
      end
    end


    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post eliminado satisfactoriamente'
    end

    def destroy_multiple
      Post.destroy redefine_ids(params[:multiple_ids])
      redirect_to posts_path(page: @current_page, search: @query), notice: "Posts eliminados satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      def set_categories
        @categories = Category.order(:name)
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:title, :body, :user_id, :category_id, :subcategory_id, :image, :view, :public, :comments_open, :shared_enabled, :permalink, :tag_list)
      end
  end
end

keppler_blog/app/helpers/keppler_blog/application_helper.rb
module KepplerBlog
  module ApplicationHelper
 
  end
end

keppler_blog/app/views/keppler_blog/posts/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.library_books.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Módulo de posts
		%p Aquí podrá gestionar el contenido de todos los posts del blog, podrá recopilar cronológicamente textos o artículos de uno o varios autores, apareciendo primero el más reciente, tiene opciones de agregar banner principal y organizarción por categorías y subcategorías.

keppler_blog/app/views/keppler_blog/posts/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to posts_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @post do |f|
					.row
						= f.input :image, :as => :file_material, label: false, wrapper_html: { class: "file-field" }
						= f.input :title, label: "Título", input_html: { style: "z-index: 1;" }	
						= f.input :body, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'mini'} }
						= f.input :category_id, collection: @categories, label: false, include_blank: "Selecione una categoría", input_html: { class: "browser-default" }
						= f.input :subcategory_id, collection: f.object.created_at? ? f.object.category.subcategories : [], label: false, include_blank: "Selecione una subcategoría", input_html: { class: "browser-default" }
						= f.input :tag_list, label: false, input_html: { data:{role:'tagsinput'}, value:  f.object.tag_list.reverse.join(", "), placeholder: "Agregar tags" }
						= f.input :public, as: :checkbox_material, label: 'Publicar'
						= f.input :comments_open, as: :checkbox_material, label: 'Comentarios'
						= f.input :shared_enabled, as: :checkbox_material, label: 'Compartir en redes'
					
						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

- unless @post.subcategory_id
	:javascript
		$('#post_subcategory_id').prop('disabled', true)
		$('#post_subcategory_id').hide()

- if @post.image.file
	:javascript
		$('.file-path').val("#{@post.image.file.filename}")
		
:javascript
	$(".input-field").css("z-index", "1");

keppler_blog/app/views/keppler_blog/posts/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, model
			= link_to edit_post_path(@post), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.library_books.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card#blog-listing--show-body{ resize: true , style: "height: {{windowHeight}}px;" }
	= image_tag @post.image
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @post.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.title")
			.display-value= @post.title
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.permalink")
			.display-value= @post.permalink
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.body")
			.display-value= sanitize(@post.body, tags: []).truncate(300)
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.user_id")
			.display-value= @post.user.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.category_id")
			.display-value= @post.category.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.subcategory_id")
			.display-value= @post.subcategory ? @post.subcategory.name : "Sin subcategoría"
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.public")
			.display-value= @post.public ? "Si" : "No"
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.comments_open")
			.display-value= @post.comments_open ? "Si" : "No"
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.shared_enabled")
			.display-value= @post.shared_enabled ? "Si" : "No"
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.created_at")
			.display-value= @post.created_at.strftime("%d/%m/%Y %H:%M:%S")
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.updated_at")
			.display-value= @post.updated_at.strftime("%d/%m/%Y %H:%M:%S")
	

:javascript
	$('.tooltipped').tooltip({delay: 1});

keppler_blog/app/views/keppler_blog/posts/_listing.html.haml
%tr{ id: "row-#{post.id}" }
	- if can? :destroy_multiple, model
		%td.item-check{style:"width: 5%"}
			= link_to "", post_path(post), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{post.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{post.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{post.id}" }
	%td{style:"width: 60%"}
		= link_to "", post_path(post, search: @query), remote: true, class: "show-row tooltipped", "data-position" => "bottom", "data-tooltip" => "#{post.title}"
		%span
			= post.title.truncate(70)
	%td.hide-on-small-and-down{style:"width: 10%"}
		= link_to "", post_path(post, search: @query), remote: true, class: "show-row"
		%span
			= post.user.name
	%td.hide-on-small-and-down{style:"width: 10%"}
		= link_to "", post_path(post, search: @query), remote: true, class: "show-row"
		%span
			= post.category.name
	%td.hide-on-small-and-down{style:"width: 10%"}
		= link_to "", post_path(post, search: @query), remote: true, class: "show-row"
		%span
			= post.public ? "Publicado" : "No publicado"						
	%td{style:"width: 5%"}		
		= link_to post_path(post), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

keppler_blog/app/views/keppler_blog/posts/edit.html.haml
= title "Posts - editar | #{@post.id}"
= render 'form'

keppler_blog/app/views/keppler_blog/posts/index.html.haml
= title("Posts - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_post_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only", "data-no-turbolink" => true do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |post|
				= render 'listing', post: post
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado posts.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"


= link_to new_post_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
	= material_icon.md_24.add.css_class("md-light")

keppler_blog/app/views/keppler_blog/posts/new.html.haml
= title "Posts - Nuevo"
= render 'form'

keppler_blog/app/views/keppler_blog/posts/show.html.haml
= title "Posts | #{@post.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, model
				= link_to post_path(@post), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: '¿Estas seguro de querer eliminar?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, model
				= link_to edit_post_path(@post), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to posts_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card{ style: "padding: 0px;"}
			.card-image
				= image_tag @post.image
			.card-content
				%ul.list{ style: "margin:0px;"}
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.title")
						.display-value.fs-body-1.tc-black-2= @post.title.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.permalink")
						.display-value.fs-body-1.tc-black-2= @post.permalink.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.body")
						.display-value.fs-body-1.tc-black-2=  @post.body.html_safe
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.user_id")
						.display-value.fs-body-1.tc-black-2= @post.user.name
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.category_id")
						.display-value.fs-body-1.tc-black-2= @post.category.name
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.subcategory_id")
						.display-value.fs-body-1.tc-black-2= @post.subcategory ? @post.subcategory.name : "Sin subcategoría"
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.public")
						.display-value.fs-body-1.tc-black-2= @post.public ? "Si" : "No"
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.comments_open")
						.display-value.fs-body-1.tc-black-2= @post.comments_open ? "Si" : "No"
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.shared_enabled")
						.display-value.fs-body-1.tc-black-2= @post.shared_enabled ? "Si" : "No"
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.created_at")
						.display-value= @post.created_at.strftime("%d/%m/%Y %H:%M:%S")
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.updated_at")
						.display-value= @post.updated_at.strftime("%d/%m/%Y %H:%M:%S")
				

keppler_blog/app/views/keppler_blog/posts/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@post.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");

keppler_blog/app/views/keppler_blog/posts/subcategories_of_cagegory.js.erb
<%- unless @subcategories.empty? %>
	$('#post_subcategory_id').prop('disabled', false)
	$('#post_subcategory_id').show()
	$('#post_subcategory_id').html('<%= escape_javascript(options_for_select(@subcategories.map { |s| [s.name, s.id] }))%>');
<%- else %>
	$('#post_subcategory_id').html('<%= escape_javascript(options_for_select(["", "No hay opciones"]))%>');
	$('#post_subcategory_id').prop('disabled', true)
	$('#post_subcategory_id').hide()
<%- end %>